# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c464008f665bda5e17d7d92ffac9e775050b606c66def9f9116034e356815f368648424a643e58ab53c5d988bb83e8953fe76f98124432f17645bd85769503f4

test:
  secret_key_base: aa01370fff2286804a502527272f54d8b7fe8702f0a15ccd9e14847dadd79a303966e4a91a8599be596907bc7d8d16d19222a3716d54e06cb9b5dc06820ce705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
